// User Position //
export const FROM_POINT_SELECTED = 'FROM_POINT_SELECTED';
export const TO_POINT_SELECTED = 'TO_POINT_SELECTED';

export const GET_NEARBY_STOPS = 'GET_NEARBY_STOPS';

export const REVERSE_POINTS = 'REVERSE_POINTS';

export const UPDATE_SETTING = 'UPDATE_SETTING';
export const UPDATE_MULTI_SETTING = 'UPDATE_MULTI_SETTING';

export const ADD_PAST_SEARCH = 'ADD_PAST_SEARCH';

export const SET_ITINERARIES = 'SET_ITINERARIES';
export const SELECT_ITINERARY = 'SELECT_ITINERARY';
export const UNSET_ITINERARIES = 'UNSET_ITINERARIES';
export const SET_SUMMARY_POPUP_VISIBLE = 'SET_SUMMARY_POPUP_VISIBLE';
export const REMOVE_ITINERARIES_ERROR = 'REMOVE_ITINERARIES_ERROR';
export const UPDATE_POLYLINE_COLORS = 'UPDATE_POLYLINE_COLORS';

export const WITHOUT_GEOLOC = 'WITHOUT_GEOLOC';

export const SET_DEPARTURE_SETTINGS = 'SET_DEPARTURE_SETTINGS';
export const SET_SELECTED_VEHICLE = 'SET_SELECTED_VEHICLE';
